spring:
  application:
    name: asserter-project
  datasource:
    url: jdbc:mysql://localhost:3306/appdatabase
    username: root
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
server:
  port: 8081

jwt:
  secret: "K1LL4rB123"


